build:
    environment:
        php:
            version: '5.6'
    tests:
        override:
            - phpcs-run --standard=phpcs.xml

filter:
    excluded_paths: ['tests/*', 'vendor/*']

checks:
    php:
        code_rating: true
        duplication: true
