build:
    environment:
        php:
            version: '5.6'
        mysql: false
        postgresql: false
        mongodb: false
        elasticsearch: false
        redis: false
        memcached: false
        neo4j: false
        rabbitmq: false
#    tests: true
#        override:
#            - phpcs-run --standard=phpcs.xml src
#            - phpunit

filter:
    excluded_paths: ['tests/*', 'vendor/*']

checks:
    php:
        code_rating: true
        duplication: true
